config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends1s
  # resources :friends
  # get 'home/index'
  get 'home/about'
  # root 'home#index'
  root 'friends1s#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/friends1.rb
class Friends1 < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends1s_controller.rb
class Friends1sController < ApplicationController
  before_action :set_friends1, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /friends1s or /friends1s.json
  def index
    @friends1s = Friends1.all
  end

  # GET /friends1s/1 or /friends1s/1.json
  def show
  end

  # GET /friends1s/new
  def new
    @friends1 = Friends1.new
  end

  # GET /friends1s/1/edit
  def edit
  end

  # POST /friends1s or /friends1s.json
  def create
    @friends1 = Friends1.new(friends1_params)

    respond_to do |format|
      if @friends1.save
        format.html { redirect_to @friends1, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friends1 }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friends1.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends1s/1 or /friends1s/1.json
  def update
    respond_to do |format|
      if @friends1.update(friends1_params)
        format.html { redirect_to @friends1, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friends1 }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friends1.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends1s/1 or /friends1s/1.json
  def destroy
    @friends1.destroy
    respond_to do |format|
      format.html { redirect_to friends1s_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friends1 = current_user.friends1.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized to Edit this friend" if @friends1.nil?

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friends1
      @friends1 = Friends1.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friends1_params
      params.require(:friends1).permit(:first_name, :last_name, :email, :phone, :instagram, :user_id)
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone_string, :instagram)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends1s_helper.rb
module Friends1sHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends1s/_form.html.erb
 <br>
<%= form_with(model: friends1) do |form| %>
  <% if friends1.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friends1.errors.count, "error") %> prohibited this friends from being saved:</h2>

      <ul>
        <% friends1.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="field form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.text_field :instagram, class:"form-control", placeholder:"Instagram ID" %>
  </div><br>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>
  

 <!--  <%= current_user.id %> -->

  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
  <br>
<% end %>

app/views/friends1s/edit.html.erb
 <br>
<h1>Editing Friends</h1>

<%= render 'form', friends1: @friends1 %>

<%= link_to 'Show', @friends1, class:"btn btn-dark" %>
<%= link_to 'Back', friends1s_path, class:"btn btn-dark" %>

app/views/friends1s/index.html.erb
<!-- <p id="notice"><%= notice %></p>
 -->
<!-- <h1>Friend List</h1> -->
<% if user_signed_in? %>
    <table class="table table-bordered table-striped table-hover">
      <thead class="table-dark">
        <tr>
          <th>First name</th>
          <th>Last name</th>
          <th>Email</th>
          <th>Phone</th>
          <th>Instagram</th>
          <th>User Id</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @friends1s.each do |friends1| %>
          <tr>
            <td><%= friends1.first_name %></td>
            <td><%= friends1.last_name %></td>
            <td><%= friends1.email %></td>
            <td><%= friends1.phone %></td>
            <td><%= friends1.instagram %></td>
            <td><%= friends1.user_id %></td>
            <td><%= link_to 'Show', friends1, class:"btn btn-outline-secondary btn-sm" %></td>

            <% if friends1.user == current_user %>
              <td><%= link_to 'Edit', edit_friends1_path(friends1), class:"btn btn-outline-primary btn-sm" %></td>
              <td><%= link_to 'Delete', friends1, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>

            <% else %>
            <td></td>
            <td></td>
            <% end%>
          </tr>
        <% end %>
      </tbody>
    </table>

  <br>


  <%= link_to 'New Friend', new_friends1_path, class:"btn btn-secondary" %>


<% else %>
  <h1>Hello Peeps!!!</h1>
<h2>Kindly Log In to our website to add your friends</h2>
<% end %>

app/views/friends1s/new.html.erb
 <br>
<h1>Add New Friends</h1>

<%= render 'form', friends1: @friends1 %>

<%= link_to 'Back', friends1s_path, class:'btn btn-secondary' %>

app/views/friends1s/show.html.erb
<!-- <p id="notice"><%= notice %></p>
 -->
 <br>

<div class="jumbotron">
  <h1 class="display-4"><%= @friends1.first_name %> <%= @friends1.last_name %></h1>
  <br>
  <p class="lead"><%= @friends1.email %> | <%= @friends1.phone %> | <%= @friends1.instagram %></p>
  
  <br><br>
  <%= link_to 'Edit', edit_friends1_path(@friends1), class:"btn btn-secondary" %>
  <%= link_to 'Back', friends1s_path, class:"btn btn-dark" %>

</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%= link_to 'Friends App', root_path , class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       
        <li class="nav-item">
          <%= link_to "Friends", friends1s_path, class:"nav-link" %>
        </li>

        

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Add Friends", new_friends1_path, class:"nav-link" %>
          </li>
            <li class="nav-item">
           <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>

       
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up",  new_user_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign In",  new_user_session_path, class:"nav-link" %>
          </li>
          <% end %>
          
           <li class="nav-item">
          <%= link_to "About Us", home_about_path, class:"nav-link" %>
        </li>
 		  
          
        </li>
        
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Hello Peeps!!!</h1>
<h2>Kindly Log In to our website to add your friends</h2>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Friends App</title>

     <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>

    <%= yield %>  
   </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>